
export default function About(){
    return <>
       <h1>Page About</h1>   
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus dui, aliquet eget sem eu, dignissim commodo diam. Curabitur ac ipsum sapien. Maecenas imperdiet tempor libero, eget tempor erat interdum sit amet. Maecenas in neque in arcu consequat vestibulum imperdiet eget mi. Proin tristique posuere quam at mattis. Pellentesque in condimentum leo. Fusce rutrum nisl in nulla tincidunt, in laoreet est porttitor. Nulla non malesuada mauris. Maecenas a neque et arcu dictum pretium sit amet vitae turpis. Aliquam gravida interdum sapien quis sollicitudin. Aenean quis semper libero. Vivamus quis enim eu leo aliquet posuere. Nulla ac ipsum et massa egestas bibendum. Etiam nulla sem, feugiat a mi sed, ullamcorper vulputate mi. Fusce ac tortor ac nibh iaculis euismod sed nec odio. Aenean malesuada libero lectus, at auctor turpis vestibulum id.

Nunc eget vehicula urna, eu elementum purus. Maecenas nec iaculis ligula. Curabitur non porta ex, vel feugiat justo. Nulla in quam eget mi pretium venenatis a eget augue. Morbi sed efficitur lacus, a commodo tellus. Curabitur venenatis venenatis ex, a eleifend orci mattis lacinia. Donec nunc est, volutpat ac enim id, vehicula volutpat urna. Sed dapibus metus ipsum, at posuere ligula posuere at. Vestibulum nec velit elementum, iaculis ipsum vitae, suscipit dolor. Cras a lectus ac urna posuere fringilla nec eu felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac dui quis purus fermentum aliquam. Quisque hendrerit massa eu bibendum pulvinar. Pellentesque mollis maximus volutpat. Fusce non turpis quis augue bibendum ornare.

Proin auctor magna sed nisi consequat, eu elementum ex auctor. Duis laoreet nisi eu massa ornare, ut gravida purus accumsan. Pellentesque fringilla leo eu orci iaculis lobortis et eu quam. Mauris in nulla et leo tincidunt iaculis. Sed pulvinar mi non lorem malesuada consectetur. Praesent ornare sapien vitae risus tristique, a dignissim justo pretium. Duis dignissim vulputate magna eu gravida.

Pellentesque sollicitudin posuere urna. Phasellus lacus risus, venenatis quis ipsum quis, molestie aliquam nisl. Phasellus nec nunc arcu. Aenean sagittis et purus ut faucibus. Maecenas a augue mauris. Donec gravida consequat lorem, vitae fermentum est blandit ac. Nunc at tellus mauris. Donec porttitor eleifend ante, at aliquet ante faucibus efficitur. Donec at arcu a felis lobortis egestas eget ut turpis. Nulla a varius nulla, ac aliquet arcu. Maecenas sit amet facilisis tellus, ac pellentesque tortor. Aliquam maximus ex vitae elementum euismod. Suspendisse tempor ultrices libero convallis ornare. Nullam gravida velit quis est congue malesuada. Nam quam augue, efficitur sed viverra id, maximus et ligula.

Donec consectetur laoreet enim nec placerat. Donec id ex id velit faucibus ultrices. Morbi laoreet hendrerit leo, sit amet ullamcorper est egestas nec. Donec eget lacus eu purus pharetra tincidunt eu quis neque. Nulla pellentesque augue velit, luctus finibus enim vulputate a. Pellentesque feugiat feugiat suscipit. Donec luctus metus turpis, eu ultrices nulla dignissim non.</p>
    </>
}